services:
  anime-tracker:
    image: ghcr.io/napandee/anime-tracker:latest
    container_name: anime-tracker
    restart: unless-stopped
    ports:
      - "8889:8888"
    env_file:
      - ***REDACTED-PATH***/anime-tracker/.env
